# -*- coding: utf-8 -*-
"""volume_of_sphere.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YwkNGfi6WclNPtHW4pko6butaffhVbwr
"""

def calculate_volume_of_sphere(r):
  volume = (4/3)*(3.14)*(r*r*r)
  return volume

radius1 = 30
print(f"The volume of a sphere with radius = {radius1} = {calculate_volume_of_sphere(radius1)}")
radius2 = 40
print(f"The volume of a sphere with radius = {radius2} = {calculate_volume_of_sphere(radius2)}")